---
# tasks file for app
- name: (APP) Update repositories cache and install required packages
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name: "{{ packages }}"
    force_apt_get: true
  vars:
    packages:
    - aptitude
    - python-apt
    - python3-pip
    - python3-dev
    - build-essential
    - libssl-dev
    - libffi-dev
    - virtualenv
    - python3-setuptools
    - python3-pexpect
    - nginx
    

  tags:
    - packages

- name: (APP) Enable UFW to manage firewall traffic and enable Openssh
  ufw:
    state: enabled
    rule: allow
    name: OpenSSH

- name: (APP) Allow all outbound traffic through firewall
  ufw:
     rule: allow
     direction: out
     to_ip: any

- name: (APP) Allow traffic from OSSEC Servers for ossec server manager
  ufw:
    rule: allow
    from_ip: "{{ item }}"
    to_port: '1514'
    proto: udp
  loop:
    - "{{ groups['ossecservers'] | map('extract', hostvars, ['ansible_host']) | join(',') }}"

- name: (APP) Copy the helloworld application directory to the app server
  copy:
    src: ../../../helloworld/
    dest: "{{ application_dir }}"
    owner: vagrant
    group: www-data
  
- import_tasks: app.yml
